DROP TABLE ACCOUNT;
DROP TABLE CREDIT;
DROP TABLE CLIENT;

CREATE TABLE IF NOT EXISTS CLIENT (
    id BIGINT NOT NULL AUTO_INCREMENT,
    typeId VARCHAR(50) NOT NULL,
    clientId VARCHAR(50) NOT NULL,
    firstName VARCHAR(50),
    lastName VARCHAR(50),
    email VARCHAR(50),
    PRIMARY KEY (id),
    INDEX IND_CLIENT_1 (typeId , clientId)
)  AUTO_INCREMENT=1
;

CREATE TABLE IF NOT EXISTS CREDIT (
    id BIGINT NOT NULL AUTO_INCREMENT,
    clientId BIGINT NOT NULL,
    creditValue DECIMAL NOT NULL,
    approvalDate DATE NOT NULL,
    paidDate DATE,
    FOREIGN KEY (clientId)
        references CLIENT (id),
    PRIMARY KEY (id)
)  AUTO_INCREMENT=1
;
  
CREATE TABLE IF NOT EXISTS ACCOUNT (
    id BIGINT NOT NULL AUTO_INCREMENT,
    number VARCHAR(50) NOT NULL,
    clientId BIGINT NOT NULL,
    total DECIMAL NOT NULL,
    blocked BOOLEAN,
    PRIMARY KEY (id),
    FOREIGN KEY (clientId)
        references CLIENT (id)
)  AUTO_INCREMENT=1
;